### ISSUE TITLE
Doesn't work with cmd

### ISSUE THREAD

**Issue by jooapa** [Antonako1/ATK#1]
I leave this issue for the purposes of the cmd not working with the command "atk -l"
It sopused to return the absolute path to the atk.exe but it only return string "atk"
![image](https://github.com/Antonako1/ATK/assets/37744313/1e5c76a8-4456-4591-9889-e08cda7f2ad9)

**Comment by jooapa** [comment]
pelle

**Comment by jooapa** [comment]
PRoblem is still founded in the version 1.1.0

**Comment by Antonako1** [comment]
https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.3

**Comment by jooapa** [comment]
what is bro yappin about, doesn't fix the problem, issue is still present 🤡
